routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('auth/{provider}', ['as' => 'socialite_login', 'uses' => 'Auth\LoginController@redirectToProvider']);
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');


Route::group(['middleware' => 'auth'], function(){
	Route::get('/', 'SiteController@index')->name('site-home');
	Route::get('/admin', 'AdminController@index')->name('admin-login');
	#admin
	Route::get('admin/dashboard', 'DashboardController@index')->name('admin_dashboard');
	Route::get('admin/orders', 'DashboardController@check_orders')->name('admin_check_orders');
	Route::get('admin/order-details/{id}', 'DashboardController@check_order_details')->name('admin_check_order_details');

	Route::get('admin/receive-order/{id}', 'DashboardController@receive_order')->name('admin_receive_order');
	Route::get('admin/set-delivery-boy/{id}', 'DashboardController@set_delivery_boy')->name('admin_set_delivery_boy');

	Route::get('admin/create-account', 'DashboardController@create_account')->name('admin_create_account');
	Route::post('admin/add-account', 'DashboardController@add_account')->name('admin_add_account');

	#category
	Route::get('admin/categories', 'CategoryController@index')->name('admin_category');
	Route::get('admin/add-category', 'CategoryController@add_category_page')->name('admin_add_category_page');

	Route::get('admin/edit-category/{id}', 'CategoryController@edit_category_page')->name('admin_edit_category_page');
	Route::get('admin/remove-category/{id}', 'CategoryController@remove_category')->name('admin_remove_category');

	Route::post('admin/verify-category', 'CategoryController@verify_category')->name('admin_verify_category');

	#menu 
	Route::get('admin/menu-list', 'MenuController@index')->name('admin_menu');
	Route::get('admin/add-menu', 'MenuController@add_menu_page')->name('admin_add_menu_page');
	Route::get('admin/edit-menu', 'MenuController@edit_menu_page')->name('admin_edit_menu_page');
	Route::post('admin/verify-menu', 'MenuController@verify_menu')->name('admin_verify_menu');

	Route::get('admin/edit-menu/{id}', 'MenuController@edit_menu_page')->name('admin_edit_menu_page');
	Route::get('admin/remove-menu/{id}', 'MenuController@remove_menu')->name('admin_remove_menu');

	#menu-price
	Route::get('admin/manage-sizes/{id}', 'MenuController@manage_sizes')->name('admin_manage_sizes');
	Route::post('admin/add-price-size/', 'MenuController@add_price_size')->name('admin_add_price_size');
	Route::get('admin/remove-menu-price/{id}/{pid}', 'MenuController@remove_menu_price')->name('admin_remove_menu_price');

	#sizes
	Route::get('admin/menu-sizes', 'SizesController@index')->name('menu_sizes');
	Route::get('admin/add-menu-sizes', 'SizesController@add_menu_sizes')->name('add_menu_sizes');
	Route::post('admin/verify-added-size', 'SizesController@verify_added_size')->name('admin_verify_added_size');

	Route::get('admin/remove-size/{id}', 'SizesController@remove_size')->name('admin_remove_size');

	################## USER #############################
	Route::get('user/dashboard', 'UserDashboardController@index')->name('user_dashboard');
	Route::post('user/update-info', 'UserDashboardController@update_info')->name('user_update_info');

	Route::get('user/get-menu', 'UserMenuController@get_menu')->name('user_get_menu');
	Route::post('user/add-to-cart', 'UserMenuController@add_to_cart')->name('add_to_cart');

	Route::get('user/view-cart', 'CartController@view_cart')->name('user_view_cart');
	Route::get('user/remove-cart-item/{id}', 'CartController@user_remove_cart_item')->name('user_remove_cart_item');

	Route::post('user/submit-order', 'CartController@submit_order')->name('user_submit_order');
	Route::get('user/success-order/{id}', 'CartController@success_order')->name('user_success_order');

	Route::get('user/menu', 'UserMenuController@index')->name('user_menu');
	Route::get('user/orders', 'UserMenuController@user_orders')->name('user_orders');
	Route::get('user/order-details/{id}', 'UserMenuController@user_order_details')->name('user_order_details');
	Route::get('user/order-location/{id}', 'UserMenuController@user_order_location')->name('order_location');

	######## Delivery Boy #################
	Route::get('delivery/dashboard', 'DeliveryController@index')->name('deliveryboy_dashboard');	
	Route::get('delivery/{id}', 'DeliveryController@selectOrder')->name('deliveryboy_order');
	Route::post('delivery/location', 'DeliveryController@saveLocation')->name('deliveryboy_location');
});

app/OnlineTransaction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OnlineTransaction extends Model
{
    protected $connection = 'mysql2';

    public $table = 'online_transaction';
    public $fillable = ['transaction_date', 'transaction_time', 'user_id', 'created_at', 'has_change'];  
    public $timestamps = false;
    
    public function user()
    {
        return \App\User::find($this->user_id);
    }

    public function online_transaction_menu()
    {
        return $this->belongsTo('App\OnlineTransactionMenu', 'id', 'transaction_id');
    }

    public function menus()
    {
        return $this->hasMany('App\OnlineTransactionMenu');
    }

    public function getTransactionNumberAttribute()
    {

        return str_pad($this->id, 10, '0', STR_PAD_LEFT);
    }

    public function getCurrentStatusAttribute()
    {
    	switch($this->status) 
    	{
    		case 1:
                return '<i class=" fas fa-spinner fa-pulse  has-text-warning"></i> Pending';
            break;
            case 2:
                return '<i class="fas fa-check-circle has-text-success"></i> Received';
            break;
            case 3:
                return 'Preparing Order';
            break;
    	}
    }
    public function getChangeStatusAttribute()
    {
        switch($this->status)
        {
            case 1:
                return '<a href="'. route('admin_receive_order', $this->id) .'" title="Receive Order">
                            <span class="icon has-text-success is-clearfix"><i class="fas fa-check "></i></span>
                        </a>';
            break;

            case 2:
              return '<a href="#" title="Pending for delivery"><span class="icon has-text-dark is-clearfix"><i class="fas fa-stopwatch"></i></span></a>';
            break;

        }
    }

    
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    public $table = 'users';
    public $timestamps = true;

    protected $fillable = [
        'email', 'name', 'contact_number', 'address', 'username', 'password', 'access', 'remember_token', 'created_at', 'updated_at', 'deleted_at', 'provider', 'provider_id'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function cart()
    {
        return $this->hasMany('App\Cart');
    
    }

    public function transaction()
    {
        return $this->hasMany('App\Transaction');
    
    }

}

resources/views/user/orders/details.blade.php
@extends('layouts.user-dashboard')
@section('title', 'Order Details')
@section('content')

<section class="hero is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Order Details
      </h1>
      <h2 class="subtitle">
        Order No : {{ str_pad($order->id, 10, '0', STR_PAD_LEFT) }}
      </h2>
    </div>
  </div>
</section>

<div class="container is-clearfix">
  <div class="columns is-marginless">
    <div class="column is-4">
      <table class="table is-bordered">
        <tbody>
          <tr>
            <td><strong>Order No.</strong></td>
            <td>{{ $order->transaction_number }}</td>
          </tr>
          <tr>
            <td><strong>Order Details</strong></td>
            <td>
              @foreach($order_menus as $menu)
                <p>{{ $menu->quantity }} x {{ $menu->menu->menu }}</p>
              @endforeach
            </td>
          </tr>
          <tr>
              <td><strong>Total Amount</strong></td>
              <td>{{ number_format($menu->pricing->price * $menu->quantity, 2) }}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="column is-8">
      <div id="map" style="width:100%; height: 500px">Loading Map...</div>
    </div>
  </div>
</div>
<hr>
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        Mama and Sons &copy; 2018
      </p>
    </div>
  </div>
</footer>
<script async defer src="https://maps.googleapis.com/maps/api/js?key={{ getenv('GOOGLE_API') }}&callback=getPoints"></script>
<script type="text/javascript">
  setInterval(function(){ 
      getPoints();
  }, 5000);

  function getPoints()
  {
    $.get("{{ route('order_location', $order->id) }}",showMap);
  }

  function showMap(response) {
    var $map = document.getElementById('map');
    var position = { lat: parseFloat(response.lat), lng: parseFloat(response.long) };
    window.map = new google.maps.Map($map, {
      center: position,
      zoom: 15
    });

    console.log(map);
    window.markers = window.markers || [];
    var marker = new google.maps.Marker({ map: map, position: position });
  }
</script>
@endsection

resources/views/user/orders/index.blade.php
@extends('layouts.user-dashboard')
@section('title', 'Orders')
@section('content')

<section class="hero is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        My Orders
      </h1>
    </div>
  </div>
</section>

<div class="container is-clearfix">
  <div class="columns is-marginless">
    <div class="column"></div>
    <div class="column is-10">
      <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
        <thead>
          <tr>
            <th width="35%" class="has-text-centered">Order No  </th>
            <th width="35%">Transaction Date</th>
            <th width="30%">Status </th>
          </tr>
        </thead>
        <tbody>
          @forelse ($transactions as $transaction)
            <tr>
              <td class="has-text-centered">
                <a href="{{ route('user_order_details', $transaction->id) }}">
                  {{ $transaction->transaction_number }}
                </a>
              </td>
              <td>{{ $transaction->transaction_date }} {{ $transaction->transaction_time }}</td>
              <td>{!! $transaction->current_status !!}</td>
            </tr>
          @empty
            <tr>
              <td colspan="3" class="has-text-centered">No active transaction.</td>
            </tr>
          @endforelse
        </tbody>
      </table>
    </div>
    <div class="column"></div>
  </div>
</div>
<hr>
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        Mama and Sons &copy; 2018
      </p>
    </div>
  </div>
</footer>
<script type="text/javascript"></script>
@endsection